apiVersion: v2
name: monitoring
description: Prometheus stack
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "81.4.2"
    repository: https://prometheus-community.github.io/helm-charts
