apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app  # <--- Service też musi mieć ten label!
spec:
  type: NodePort
  selector:
    app: my-app # Musi pasować do Deploymentu
  ports:
  - name: http       # <--- BARDZO WAŻNE: ServiceMonitor szuka tej nazwy
    port: 80         # Port na zewnątrz serwisu
    targetPort: 8080 # <--- POPRAWKA: Musi być 8080, bo tu słucha Twoja apka w Go
    nodePort: 30080