namespace: my-app

replicas:
- name: my-app
  count: 1
images:
- name: 424432388155.dkr.ecr.us-east-1.amazonaws.com/antonputra/app-lesson-268
  # 2. 'newName' to jest nazwa Twojego nowego obrazu
  newName: karol0945/go-crypto-k8s
  # 3. 'newTag' to wersja
  newTag: v0.1.7
resources:
- ../../base